bioimageio_core_version: 0.5.5
bioimageio_spec_version: 0.4.7
rdf_sha256: f8472cbf4a77d3bc68bfbb7473355499e5d62f55ebf75b03018df05a5e1c0ec9
status: failed
tests:
  bioimageio:
  - bioimageio_spec_version: 0.4.7
    error: null
    name: bioimageio.spec static validation of model RDF 0.4.7 with update to latest
      format version
    nested_errors: {}
    status: passed
    traceback: null
    warnings:
      tags: 'Missing tags for categories: [{''dims'': [''2d'', ''3d'', ''2d-t'', ''3d-t'']},
        {''framework'': [''tensorflow'', ''pytorch'', ''tensorflow.js'']}, {''software'':
        [''ilastik'', ''imagej'', ''fiji'', ''imjoy'', ''deepimagej'', ''n2v'']}]'
      weights: {pytorch_state_dict: missing 'pytorch_version', torchscript: missing
          'pytorch_version'}
  - bioimageio_spec_version: 0.4.7
    error: null
    name: bioimageio.spec static validation of model RDF 0.4.7
    nested_errors: {}
    status: passed
    traceback: null
    warnings:
      tags: 'Missing tags for categories: [{''dims'': [''2d'', ''3d'', ''2d-t'', ''3d-t'']},
        {''framework'': [''tensorflow'', ''pytorch'', ''tensorflow.js'']}, {''software'':
        [''ilastik'', ''imagej'', ''fiji'', ''imjoy'', ''deepimagej'', ''n2v'']}]'
      weights: {pytorch_state_dict: missing 'pytorch_version', torchscript: missing
          'pytorch_version'}
  - bioimageio_core_version: 0.5.5
    bioimageio_spec_version: 0.4.6post3
    error: '{''format_version'': [''Must be one of: 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.4.4,
      0.4.5, 0.4.6.'']}'
    name: load resource description
    status: failed
    traceback: ["  File \"/usr/share/miniconda/envs/6647695/lib/python3.9/site-packages/bioimageio/core/resource_tests.py\",
        line 117, in test_resource\n    rd = load_resource_description(rdf, weights_priority_order=None
        if weight_format is None else [weight_format])\n", "  File \"/usr/share/miniconda/envs/6647695/lib/python3.9/site-packages/bioimageio/core/resource_io/io_.py\",
        line 47, in load_resource_description\n    raw_rd = load_raw_resource_description(source,
        update_to_format=\"latest\")\n", "  File \"/usr/share/miniconda/envs/6647695/lib/python3.9/site-packages/bioimageio/spec/io_.py\",
        line 177, in load_raw_resource_description\n    raw_rd = schema.load(data)\n",
      "  File \"/usr/share/miniconda/envs/6647695/lib/python3.9/site-packages/marshmallow/schema.py\",
        line 722, in load\n    return self._do_load(\n", "  File \"/usr/share/miniconda/envs/6647695/lib/python3.9/site-packages/marshmallow/schema.py\",
        line 909, in _do_load\n    raise exc\n"]
  - bioimageio_core_version: 0.5.5
    bioimageio_spec_version: 0.4.6post3
    error: '{''format_version'': [''Must be one of: 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.4.4,
      0.4.5, 0.4.6.'']}'
    name: load resource description
    status: failed
    traceback: ["  File \"/usr/share/miniconda/envs/6647695/lib/python3.9/site-packages/bioimageio/core/resource_tests.py\",
        line 117, in test_resource\n    rd = load_resource_description(rdf, weights_priority_order=None
        if weight_format is None else [weight_format])\n", "  File \"/usr/share/miniconda/envs/6647695/lib/python3.9/site-packages/bioimageio/core/resource_io/io_.py\",
        line 47, in load_resource_description\n    raw_rd = load_raw_resource_description(source,
        update_to_format=\"latest\")\n", "  File \"/usr/share/miniconda/envs/6647695/lib/python3.9/site-packages/bioimageio/spec/io_.py\",
        line 177, in load_raw_resource_description\n    raw_rd = schema.load(data)\n",
      "  File \"/usr/share/miniconda/envs/6647695/lib/python3.9/site-packages/marshmallow/schema.py\",
        line 722, in load\n    return self._do_load(\n", "  File \"/usr/share/miniconda/envs/6647695/lib/python3.9/site-packages/marshmallow/schema.py\",
        line 909, in _do_load\n    raise exc\n"]
  ilastik: []
