bioimageio_core_version: 0.5.5
bioimageio_spec_version: 0.4.7
rdf_sha256: c7c31846fc7daf111a0ac81d83a3bb89fe0ea218e6e4572a83c58bfc8d419ca8
status: failed
tests:
  bioimageio:
  - bioimageio_spec_version: 0.4.7
    error: null
    name: bioimageio.spec static validation of model RDF 0.4.7 with update to latest
      format version
    nested_errors: {}
    status: passed
    traceback: null
    warnings:
      tags: 'Missing tags for categories: [{''framework'': [''tensorflow'', ''pytorch'',
        ''tensorflow.js'']}, {''software'': [''ilastik'', ''imagej'', ''fiji'', ''imjoy'',
        ''deepimagej'', ''n2v'']}]'
      weights: {torchscript: missing 'pytorch_version'}
  - bioimageio_spec_version: 0.4.7
    error: null
    name: bioimageio.spec static validation of model RDF 0.4.7
    nested_errors: {}
    status: passed
    traceback: null
    warnings:
      tags: 'Missing tags for categories: [{''framework'': [''tensorflow'', ''pytorch'',
        ''tensorflow.js'']}, {''software'': [''ilastik'', ''imagej'', ''fiji'', ''imjoy'',
        ''deepimagej'', ''n2v'']}]'
      weights: {torchscript: missing 'pytorch_version'}
  - bioimageio_core_version: 0.5.5
    bioimageio_spec_version: 0.4.6post3
    error: '{''format_version'': [''Must be one of: 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.4.4,
      0.4.5, 0.4.6.'']}'
    name: load resource description
    status: failed
    traceback: ["  File \"/usr/share/miniconda/envs/6647674/lib/python3.10/site-packages/bioimageio/core/resource_tests.py\",
        line 117, in test_resource\n    rd = load_resource_description(rdf, weights_priority_order=None
        if weight_format is None else [weight_format])\n", "  File \"/usr/share/miniconda/envs/6647674/lib/python3.10/site-packages/bioimageio/core/resource_io/io_.py\",
        line 47, in load_resource_description\n    raw_rd = load_raw_resource_description(source,
        update_to_format=\"latest\")\n", "  File \"/usr/share/miniconda/envs/6647674/lib/python3.10/site-packages/bioimageio/spec/io_.py\",
        line 177, in load_raw_resource_description\n    raw_rd = schema.load(data)\n",
      "  File \"/usr/share/miniconda/envs/6647674/lib/python3.10/site-packages/marshmallow/schema.py\",
        line 722, in load\n    return self._do_load(\n", "  File \"/usr/share/miniconda/envs/6647674/lib/python3.10/site-packages/marshmallow/schema.py\",
        line 909, in _do_load\n    raise exc\n"]
  deepimagej:
  - {bioimageio_spec_version: 0.4.8post1, name: Reproduce test outputs with DeepImageJ
      headless, status: passed}
  ilastik:
  - bioimageio_core_version: 0.5.7
    bioimageio_spec_version: 0.4.8
    error: null
    name: load resource description
    status: passed
    traceback: null
    warnings: {}
  - {error: null, name: has expected resource type, status: passed, traceback: null}
  - bioimageio_core_version: 0.5.7
    bioimageio_spec_version: 0.4.8
    error: null
    name: All URLs and paths available
    nested_errors: null
    status: passed
    traceback: null
    warnings: {}
  - bioimageio_core_version: 0.5.7
    bioimageio_spec_version: 0.4.8
    error: null
    name: Test documentation completeness.
    status: passed
    traceback: null
    warnings: {documentation: No '# Validation' (sub)section found.}
  - bioimageio_core_version: 0.5.7
    bioimageio_spec_version: 0.4.8
    error: No module named 'onnxruntime'
    name: reproduce test outputs from test inputs
    status: failed
    traceback: ["  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/resource_tests.py\",
        line 157, in _test_model_inference\n    bioimageio_model=model, devices=devices,
        weight_format=weight_format\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/prediction_pipeline/_prediction_pipeline.py\",
        line 205, in create_prediction_pipeline\n    bioimageio_model=bioimageio_model,
        devices=devices, weight_format=weight_format\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/prediction_pipeline/_model_adapters/_model_adapter.py\",
        line 132, in create_model_adapter\n    adapter_cls = _get_model_adapter(weight)\n",
      "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/prediction_pipeline/_model_adapters/_model_adapter.py\",
        line 157, in _get_model_adapter\n    from ._onnx_model_adapter import ONNXModelAdapter\n",
      "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/prediction_pipeline/_model_adapters/_onnx_model_adapter.py\",
        line 5, in <module>\n    import onnxruntime as rt\n"]
    warnings: {}
  - bioimageio_core_version: 0.5.7
    bioimageio_spec_version: 0.4.8
    error: null
    name: reproduce test outputs from test inputs
    status: passed
    traceback: null
    warnings:
      non-validation-warnings: ['floor_divide is deprecated, and will be removed in
          a future version of pytorch. It currently rounds toward 0 (like the ''trunc''
          function NOT ''floor''). This results in incorrect rounding for negative
          values.

          To keep the current behavior, use torch.div(a, b, rounding_mode=''trunc''),
          or for actual floor division, use torch.div(a, b, rounding_mode=''floor'').
          (Triggered internally at  /opt/conda/conda-bld/pytorch_1646755885937/work/aten/src/ATen/native/BinaryOps.cpp:607.)']
  - bioimageio_core_version: 0.5.8
    bioimageio_spec_version: 0.4.9
    error: null
    name: load resource description
    nested_errors: null
    status: passed
    traceback: null
    warnings: {}
  - bioimageio_core_version: 0.5.8
    bioimageio_spec_version: 0.4.9
    error: null
    name: All URLs and paths available
    nested_errors: null
    status: passed
    traceback: null
    warnings: {}
  - bioimageio_core_version: 0.5.8
    bioimageio_spec_version: 0.4.9
    error: null
    name: Test documentation completeness.
    status: passed
    traceback: null
    warnings: {documentation: No '# Validation' (sub)section found.}
  - bioimageio_core_version: 0.5.8
    bioimageio_spec_version: 0.4.9
    error: null
    name: reproduce test outputs from test inputs
    status: passed
    traceback: null
    warnings:
      non-validation-warnings: ['floor_divide is deprecated, and will be removed in
          a future version of pytorch. It currently rounds toward 0 (like the ''trunc''
          function NOT ''floor''). This results in incorrect rounding for negative
          values.

          To keep the current behavior, use torch.div(a, b, rounding_mode=''trunc''),
          or for actual floor division, use torch.div(a, b, rounding_mode=''floor'').
          (Triggered internally at  /opt/conda/conda-bld/pytorch_1646755885937/work/aten/src/ATen/native/BinaryOps.cpp:607.)']
  - bioimageio_core_version: 0.5.8
    bioimageio_spec_version: 0.4.9
    error: No module named 'onnxruntime'
    name: reproduce test outputs from test inputs
    status: failed
    traceback: ["  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/resource_tests.py\",
        line 157, in _test_model_inference\n    bioimageio_model=model, devices=devices,
        weight_format=weight_format\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/prediction_pipeline/_prediction_pipeline.py\",
        line 205, in create_prediction_pipeline\n    bioimageio_model=bioimageio_model,
        devices=devices, weight_format=weight_format\n", "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/prediction_pipeline/_model_adapters/_model_adapter.py\",
        line 132, in create_model_adapter\n    adapter_cls = _get_model_adapter(weight)\n",
      "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/prediction_pipeline/_model_adapters/_model_adapter.py\",
        line 157, in _get_model_adapter\n    from ._onnx_model_adapter import ONNXModelAdapter\n",
      "  File \"/usr/share/miniconda3/envs/ilastik-env/lib/python3.7/site-packages/bioimageio/core/prediction_pipeline/_model_adapters/_onnx_model_adapter.py\",
        line 5, in <module>\n    import onnxruntime as rt\n"]
    warnings: {}
  - bioimageio_core_version: 0.5.8
    bioimageio_spec_version: 0.4.9
    error: null
    name: reproduce test outputs from test inputs
    status: passed
    traceback: null
    warnings: {}
  - bioimageio_core_version: 0.5.7
    bioimageio_spec_version: 0.4.8
    error: null
    name: reproduce test outputs from test inputs
    status: passed
    traceback: null
    warnings: {}
