bioimageio_core_version: 0.5.3.post2
bioimageio_spec_version: 0.4.5.post11
rdf_sha256: 970aa6deaecd91da343796c243fea4885d8aacffb3d0c5e484f414d45a491d83
status: passed
tests:
  bioimageio:
  - bioimageio_spec_version: 0.4.5post11
    error: null
    name: bioimageio.spec static validation of model RDF 0.4.5 with update to latest
      format version
    nested_errors: {}
    status: passed
    traceback: null
    warnings: {tags: 'Missing tags for categories: [{''software'': [''ilastik'', ''imagej'',
        ''fiji'', ''imjoy'', ''deepimagej'', ''n2v'']}]'}
  - bioimageio_spec_version: 0.4.5post11
    error: null
    name: bioimageio.spec static validation of model RDF 0.4.5
    nested_errors: {}
    status: passed
    traceback: null
    warnings: {tags: 'Missing tags for categories: [{''software'': [''ilastik'', ''imagej'',
        ''fiji'', ''imjoy'', ''deepimagej'', ''n2v'']}]'}
  - {bioimageio_core_version: 0.5.3post2, bioimageio_spec_version: 0.4.5post11, error: null,
    name: reproduced test outputs from test inputs, status: passed, traceback: null}
  deepimagej:
  - bioimageio_core_version: 0.5.3post2
    bioimageio_spec_version: 0.4.5post7
    error: No module named 'torch'
    name: reproduce test outputs with deepimagej 2.1.13 using pytorch_state_dict weights
    reason: error
    status: failed
    traceback: ["  File \"/home/runner/work/models/models/scripts/check_rdf_and_test_model.py\",
        line 45, in test_model\n    model = load_resource_description(\n", "  File
        \"/usr/share/miniconda3/envs/deepImageJEnv/lib/python3.8/site-packages/bioimageio/core/resource_io/io_.py\",
        line 57, in load_resource_description\n    rd: ResourceDescription = resolve_raw_resource_description(raw_rd=raw_rd,
        nodes_module=nodes)\n", "  File \"/usr/share/miniconda3/envs/deepImageJEnv/lib/python3.8/site-packages/bioimageio/core/resource_io/utils.py\",
        line 113, in resolve_raw_resource_description\n    rd = SourceNodeTransformer().transform(rd)\n",
      "  File \"/usr/share/miniconda3/envs/deepImageJEnv/lib/python3.8/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 54, in transform\n    return transformer(node, **kwargs)  # noqa\n",
      "  File \"/usr/share/miniconda3/envs/deepImageJEnv/lib/python3.8/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 143, in generic_transformer\n    node, **{name: self.transform(value,
        **kwargs) for name, value in iter_fields(node)}\n", "  File \"/usr/share/miniconda3/envs/deepImageJEnv/lib/python3.8/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 143, in <dictcomp>\n    node, **{name: self.transform(value, **kwargs)
        for name, value in iter_fields(node)}\n", "  File \"/usr/share/miniconda3/envs/deepImageJEnv/lib/python3.8/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 54, in transform\n    return transformer(node, **kwargs)  # noqa\n",
      "  File \"/usr/share/miniconda3/envs/deepImageJEnv/lib/python3.8/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 63, in transform_dict\n    return {key: self.transform(value, **kwargs)
        for key, value in node.items()}\n", "  File \"/usr/share/miniconda3/envs/deepImageJEnv/lib/python3.8/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 63, in <dictcomp>\n    return {key: self.transform(value, **kwargs) for
        key, value in node.items()}\n", "  File \"/usr/share/miniconda3/envs/deepImageJEnv/lib/python3.8/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 54, in transform\n    return transformer(node, **kwargs)  # noqa\n",
      "  File \"/usr/share/miniconda3/envs/deepImageJEnv/lib/python3.8/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 143, in generic_transformer\n    node, **{name: self.transform(value,
        **kwargs) for name, value in iter_fields(node)}\n", "  File \"/usr/share/miniconda3/envs/deepImageJEnv/lib/python3.8/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 143, in <dictcomp>\n    node, **{name: self.transform(value, **kwargs)
        for name, value in iter_fields(node)}\n", "  File \"/usr/share/miniconda3/envs/deepImageJEnv/lib/python3.8/site-packages/bioimageio/spec/shared/node_transformer.py\",
        line 54, in transform\n    return transformer(node, **kwargs)  # noqa\n",
      "  File \"/usr/share/miniconda3/envs/deepImageJEnv/lib/python3.8/site-packages/bioimageio/core/resource_io/utils.py\",
        line 77, in transform_ResolvedImportableSourceFile\n    importlib_spec.loader.exec_module(dep)
        \ # type: ignore  # todo: possible to use \"loader.load_module\"?\n", '  File
        "<frozen importlib._bootstrap_external>", line 843, in exec_module

        ', '  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

        ', "  File \"/tmp/bioimageio_cache/https/zenodo.org/api/files/e1ae2d4a-a52a-4d7c-802d-892b01b263ff/unet.py\",
        line 3, in <module>\n    import torch\n"]
  ilastik:
  - {bioimageio_core_version: 0.5.1, bioimageio_spec_version: 0.4.5post3, error: "Output
      and expected output disagree:\n \nArrays are not almost equal to 4 decimals\n\nMismatched
      elements: 7518 / 1638400 (0.459%)\nMax absolute difference: 0.00075448\nMax
      relative difference: 0.00320624\n x: array([[[[[0.1346, 0.0898, 0.06  , ...,
      0.7108, 0.6976, 0.591 ],\n          [0.069 , 0.0445, 0.0313, ..., 0.7929, 0.8041,
      0.7187],\n          [0.0401, 0.0229, 0.017 , ..., 0.7752, 0.7838, 0.7582],...\n
      y: array([[[[[0.1346, 0.0898, 0.06  , ..., 0.7108, 0.6976, 0.591 ],\n          [0.0689,
      0.0445, 0.0313, ..., 0.7929, 0.8041, 0.7187],\n          [0.0401, 0.0229, 0.0169,
      ..., 0.7752, 0.7838, 0.7582],...", name: reproduce test outputs with ilastik
      1.4.0b26 using pytorch_state_dict weights, reason: error, status: failed, traceback: null}
  - {bioimageio_core_version: 0.5.3post2, bioimageio_spec_version: 0.4.5post6, error: "Output
      and expected output disagree:\n \nArrays are not almost equal to 4 decimals\n\nMismatched
      elements: 7532 / 1638400 (0.46%)\nMax absolute difference: 0.00075483\nMax relative
      difference: 0.0032108\n x: array([[[[[0.1346, 0.0898, 0.06  , ..., 0.7108, 0.6976,
      0.591 ],\n          [0.069 , 0.0445, 0.0313, ..., 0.7929, 0.8041, 0.7187],\n
      \         [0.0401, 0.0229, 0.017 , ..., 0.7752, 0.7838, 0.7582],...\n y: array([[[[[0.1346,
      0.0898, 0.06  , ..., 0.7108, 0.6976, 0.591 ],\n          [0.0689, 0.0445, 0.0313,
      ..., 0.7929, 0.8041, 0.7187],\n          [0.0401, 0.0229, 0.0169, ..., 0.7752,
      0.7838, 0.7582],...", name: reproduce test outputs with ilastik 1.4.0b27 using
      pytorch_state_dict weights, reason: error, status: failed, traceback: null}
  - {error: Missing/invalid weight formats for 10.5281/zenodo.6334583/6334584, name: reproduce
      test outputs with ilastik 1.4.0b27, reason: error, status: failed}
  - {error: Missing/invalid weight formats for 10.5281/zenodo.6334583/6334584, name: reproduce
      test outputs with ilastik 1.4.0b26, reason: error, status: failed}
